

[Proxies]
# Proxies for required interfaces
Lidar3D = "lidar3d:tcp -h localhost -p 0"
OmniRobot = "omnirobot:tcp -h localhost -p 0"






[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
